#pragma once

#include <tuinator/core/action_registry.hpp>
#include <tuinator/version.hpp>
#include <tuinator/backend/memory_backend.hpp>
#include <tuinator/core/application.hpp>
#include <tuinator/core/event.hpp>
#include <tuinator/core/geometry.hpp>
#include <tuinator/layout/box.hpp>
#include <tuinator/layout/grid.hpp>
#include <tuinator/render/canvas.hpp>
#include <tuinator/render/color.hpp>
#include <tuinator/render/style.hpp>
#include <tuinator/render/glyphs.hpp>
#include <tuinator/render/graphics_protocol.hpp>
#include <tuinator/render/terminal_image.hpp>
#include <tuinator/render/theme.hpp>
#include <tuinator/widgets/button.hpp>
#include <tuinator/widgets/bar_chart.hpp>
#include <tuinator/widgets/chart_common.hpp>
#include <tuinator/widgets/checkbox.hpp>
#include <tuinator/widgets/combo_box.hpp>
#include <tuinator/widgets/dialog.hpp>
#include <tuinator/widgets/image_view.hpp>
#include <tuinator/widgets/label.hpp>
#include <tuinator/widgets/line_chart.hpp>
#include <tuinator/widgets/list_view.hpp>
#include <tuinator/widgets/menu_bar.hpp>
#include <tuinator/widgets/menu_common.hpp>
#include <tuinator/widgets/context_menu.hpp>
#include <tuinator/widgets/command_palette.hpp>
#include <tuinator/widgets/panel.hpp>
#include <tuinator/widgets/pie_chart.hpp>
#include <tuinator/widgets/progress_bar.hpp>
#include <tuinator/widgets/scroll_view.hpp>
#include <tuinator/widgets/separator.hpp>
#include <tuinator/widgets/slider.hpp>
#include <tuinator/widgets/spinner.hpp>
#include <tuinator/widgets/split_pane.hpp>
#include <tuinator/widgets/status_bar.hpp>
#include <tuinator/widgets/tabs.hpp>
#include <tuinator/widgets/table.hpp>
#include <tuinator/widgets/text_input.hpp>
#include <tuinator/widgets/text_area.hpp>
#include <tuinator/widgets/throbber.hpp>
#include <tuinator/widgets/toggle.hpp>
#include <tuinator/widgets/tree_view.hpp>
#include <tuinator/widgets/big_text.hpp>
#include <tuinator/widgets/widget.hpp>
#include <tuinator/window/desktop.hpp>
#include <tuinator/window/window.hpp>
#include <tuinator/window/window_host.hpp>
