"""Routing data for MD domain generator – imported by _generate_md_domains.py."""

from __future__ import annotations

# Brand / logo first segments (route to MdMisc).
BRAND_FIRST = frozenset(
    {
        "500px",
        "adobe",
        "airbnb",
        "alipay",
        "amazon",
        "android",
        "angular",
        "angularjs",
        "ansible",
        "apache",
        "apple",
        "artstation",
        "atlassian",
        "aws",
        "babel",
        "bandcamp",
        "bash",
        "behance",
        "bitbucket",
        "blogger",
        "bootstrap",
        "chrome",
        "clippy",
        "codepen",
        "debian",
        "deviantart",
        "digitalocean",
        "disqus",
        "docker",
        "dribbble",
        "dropbox",
        "drupal",
        "edge",
        "elementor",
        "ember",
        "eslint",
        "etsy",
        "evernote",
        "facebook",
        "fedora",
        "figma",
        "firefox",
        "flickr",
        "foursquare",
        "github",
        "gitlab",
        "google",
        "grafana",
        "heroku",
        "houzz",
        "hubspot",
        "imdb",
        "instagram",
        "itunes",
        "jenkins",
        "jira",
        "joomla",
        "kickstarter",
        "kubernetes",
        "lastfm",
        "linkedin",
        "linux",
        "mailchimp",
        "medium",
        "meetup",
        "microsoft",
        "mozilla",
        "myspace",
        "netflix",
        "notion",
        "npm",
        "nvidia",
        "opera",
        "oracle",
        "patreon",
        "paypal",
        "pinterest",
        "playstation",
        "quora",
        "react",
        "reddit",
        "safari",
        "salesforce",
        "samsung",
        "shopify",
        "sketch",
        "skype",
        "slack",
        "snapchat",
        "sony",
        "soundcloud",
        "spotify",
        "stackoverflow",
        "steam",
        "stripe",
        "telegram",
        "terraform",
        "tiktok",
        "trello",
        "tumblr",
        "twitch",
        "twitter",
        "typescript",
        "uber",
        "ubuntu",
        "unity",
        "unreal",
        "venmo",
        "vimeo",
        "vine",
        "vk",
        "vuejs",
        "wechat",
        "whatsapp",
        "wikipedia",
        "windows",
        "wordpress",
        "xamarin",
        "xbox",
        "yahoo",
        "yarn",
        "yelp",
        "youtube",
        "zendesk",
        "nintendo",
        "playstation",
        "spotify",
        "facebook",
        "instagram",
        "whatsapp",
        "telegram",
        "wechat",
        "alipay",
        "baidu",
        "yahoo",
        "bing",
        "mozilla",
        "opera",
        "chrome",
        "firefox",
        "safari",
        "edge",
        "vivaldi",
        "brave",
        "tor",
        "npm",
        "yarn",
        "docker",
        "kubernetes",
        "terraform",
        "ansible",
        "jenkins",
        "jira",
        "confluence",
        "notion",
        "figma",
        "sketch",
        "canva",
        "shopify",
        "woocommerce",
        "wordpress",
        "drupal",
        "joomla",
        "salesforce",
        "hubspot",
        "zendesk",
        "intercom",
        "mailchimp",
        "twilio",
        "venmo",
        "coinbase",
        "binance",
        "nvidia",
        "amd",
        "intel",
        "ibm",
        "hp",
        "dell",
        "lenovo",
        "asus",
        "acer",
        "msi",
        "samsung",
        "sony",
        "tesla",
        "ford",
        "toyota",
        "honda",
        "bmw",
        "mercedes",
        "audi",
        "volkswagen",
        "porsche",
        "ferrari",
        "epic",
        "unity",
        "unreal",
        "blender",
        "autodesk",
        "atlassian",
        "bandcamp",
        "behance",
        "blogger",
        "codepen",
        "deviantart",
        "disqus",
        "dribbble",
        "etsy",
        "evernote",
        "flickr",
        "foursquare",
        "houzz",
        "imdb",
        "itunes",
        "kickstarter",
        "lastfm",
        "medium",
        "meetup",
        "myspace",
        "patreon",
        "quora",
        "shopify",
        "soundcloud",
        "stackoverflow",
        "stumbleupon",
        "tumblr",
        "vimeo",
        "vine",
        "vk",
        "wikipedia",
        "wordpress",
        "yelp",
        "zillow",
        "airbnb",
        "uber",
        "lyft",
        "doordash",
        "grubhub",
        "instacart",
        "walmart",
        "target",
        "costco",
        "ikea",
        "nike",
        "adidas",
        "puma",
        "reebok",
        "bitbucket",
        "clippy",
        "disqus",
        "deviantart",
        "codepen",
        "docker",
        "kubernetes",
        "terraform",
        "ansible",
        "jenkins",
        "jira",
        "confluence",
        "notion",
        "figma",
        "sketch",
        "canva",
    }
)

# Cross-domain first-segment overrides (checked before prefix rules).
CROSS_OVERRIDES: dict[str, str] = {
    "phone": "MdCommunication",
    "calendar": "MdTime",
    "bell": "MdAlert",
    "chart": "MdFinance",
    "book": "MdFile",
}

# (first, second, domain) compound routing rules.
MD_COMPOUND_RULES: list[tuple[str, str, str]] = [
    ("source", "branch", "MdEditor"),
    ("source", "commit", "MdEditor"),
    ("source", "fork", "MdEditor"),
    ("source", "merge", "MdEditor"),
    ("source", "pull", "MdEditor"),
    ("source", "repository", "MdEditor"),
    ("cards", "playing", "MdGame"),
    ("cards", "club", "MdGame"),
    ("cards", "diamond", "MdGame"),
    ("cards", "heart", "MdGame"),
    ("cards", "spade", "MdGame"),
    ("cards", "outline", "MdGame"),
    ("microsoft", "xbox", "MdGame"),
    ("microsoft", "windows", "MdMisc"),
    ("microsoft", "office", "MdOffice"),
    ("microsoft", "teams", "MdCommunication"),
    ("microsoft", "outlook", "MdCommunication"),
    ("microsoft", "edge", "MdMisc"),
    ("microsoft", "azure", "MdDevice"),
    ("microsoft", "excel", "MdOffice"),
    ("microsoft", "word", "MdOffice"),
    ("microsoft", "powerpoint", "MdOffice"),
    ("microsoft", "onenote", "MdOffice"),
    ("google", "chrome", "MdMisc"),
    ("google", "drive", "MdFile"),
    ("google", "maps", "MdMap"),
    ("google", "translate", "MdEditor"),
    ("google", "photos", "MdMedia"),
    ("google", "play", "MdMedia"),
    ("google", "cloud", "MdDevice"),
    ("google", "analytics", "MdFinance"),
    ("google", "ads", "MdMisc"),
    ("apple", "ios", "MdDevice"),
    ("apple", "safari", "MdMisc"),
    ("apple", "finder", "MdFile"),
    ("card", "account", "MdFinance"),
    ("card", "text", "MdFinance"),
    ("card", "bulleted", "MdEditor"),
    ("card", "outline", "MdFinance"),
    ("credit", "card", "MdFinance"),
    ("map", "marker", "MdMap"),
    ("map", "legend", "MdMap"),
    ("map", "clock", "MdMap"),
    ("map", "check", "MdMap"),
    ("map", "plus", "MdMap"),
    ("map", "minus", "MdMap"),
    ("map", "search", "MdMap"),
    ("database", "search", "MdDatabase"),
    ("database", "export", "MdDatabase"),
    ("database", "import", "MdDatabase"),
    ("database", "sync", "MdDatabase"),
    ("database", "refresh", "MdDatabase"),
    ("database", "lock", "MdDatabase"),
    ("database", "off", "MdDatabase"),
    ("database", "plus", "MdDatabase"),
    ("database", "minus", "MdDatabase"),
    ("database", "edit", "MdDatabase"),
    ("database", "remove", "MdDatabase"),
    ("database", "settings", "MdDatabase"),
    ("database", "alert", "MdDatabase"),
    ("database", "check", "MdDatabase"),
    ("database", "clock", "MdDatabase"),
    ("database", "eye", "MdDatabase"),
    ("database", "arrow", "MdDatabase"),
    ("battery", "charging", "MdBattery"),
    ("battery", "alert", "MdBattery"),
    ("battery", "bluetooth", "MdBattery"),
    ("battery", "heart", "MdBattery"),
    ("battery", "high", "MdBattery"),
    ("battery", "low", "MdBattery"),
    ("battery", "medium", "MdBattery"),
    ("battery", "off", "MdBattery"),
    ("battery", "outline", "MdBattery"),
    ("battery", "plus", "MdBattery"),
    ("battery", "minus", "MdBattery"),
    ("battery", "sync", "MdBattery"),
    ("battery", "unknown", "MdBattery"),
    ("battery", "70", "MdBattery"),
    ("battery", "80", "MdBattery"),
    ("battery", "90", "MdBattery"),
    ("battery", "40", "MdBattery"),
    ("battery", "20", "MdBattery"),
    ("battery", "10", "MdBattery"),
    ("clock", "time", "MdTime"),
    ("clock", "alert", "MdTime"),
    ("clock", "check", "MdTime"),
    ("clock", "edit", "MdTime"),
    ("clock", "plus", "MdTime"),
    ("clock", "remove", "MdTime"),
    ("clock", "outline", "MdTime"),
    ("clock", "digital", "MdTime"),
    ("clock", "analog", "MdTime"),
    ("clock", "fast", "MdTime"),
    ("clock", "slow", "MdTime"),
    ("clock", "start", "MdTime"),
    ("clock", "end", "MdTime"),
    ("clock", "in", "MdTime"),
    ("clock", "out", "MdTime"),
    ("toy", "brick", "MdGame"),
    ("toy", "brick", "MdGame"),
    ("chess", "pawn", "MdGame"),
    ("chess", "rook", "MdGame"),
    ("chess", "knight", "MdGame"),
    ("chess", "bishop", "MdGame"),
    ("chess", "queen", "MdGame"),
    ("chess", "king", "MdGame"),
    ("chess", "board", "MdGame"),
    ("dice", "1", "MdGame"),
    ("dice", "2", "MdGame"),
    ("dice", "3", "MdGame"),
    ("dice", "4", "MdGame"),
    ("dice", "5", "MdGame"),
    ("dice", "6", "MdGame"),
    ("dice", "multiple", "MdGame"),
    ("dice", "d4", "MdGame"),
    ("dice", "d6", "MdGame"),
    ("dice", "d8", "MdGame"),
    ("dice", "d10", "MdGame"),
    ("dice", "d12", "MdGame"),
    ("dice", "d20", "MdGame"),
    ("book", "open", "MdFile"),
    ("book", "account", "MdFinance"),
    ("book", "education", "MdEducation"),
    ("book", "cross", "MdReligion"),
    ("book", "bible", "MdReligion"),
    ("book", "quran", "MdReligion"),
    ("book", "music", "MdMedia"),
    ("book", "heart", "MdEmoji"),
    ("book", "skull", "MdEducation"),
    ("book", "medical", "MdHealth"),
    ("book", "alphabet", "MdEducation"),
    ("book", "cog", "MdEditor"),
    ("book", "lock", "MdSecurity"),
    ("book", "search", "MdFile"),
    ("book", "remove", "MdFile"),
    ("book", "plus", "MdFile"),
    ("book", "minus", "MdFile"),
    ("book", "edit", "MdFile"),
    ("book", "check", "MdFile"),
    ("book", "alert", "MdFile"),
    ("book", "sync", "MdFile"),
    ("book", "refresh", "MdFile"),
    ("book", "clock", "MdFile"),
    ("book", "marker", "MdFile"),
    ("book", "multiple", "MdFile"),
    ("book", "variant", "MdFile"),
    ("book", "outline", "MdFile"),
    ("book", "off", "MdFile"),
    ("book", "arrow", "MdFile"),
    ("book", "cancel", "MdFile"),
    ("book", "information", "MdFile"),
    ("book", "settings", "MdFile"),
    ("heart", "pulse", "MdHealth"),
    ("heart", "broken", "MdEmoji"),
    ("heart", "half", "MdEmoji"),
    ("heart", "outline", "MdEmoji"),
    ("heart", "circle", "MdEmoji"),
    ("heart", "box", "MdEmoji"),
    ("heart", "flash", "MdEmoji"),
    ("heart", "multiple", "MdEmoji"),
    ("heart", "settings", "MdEmoji"),
    ("heart", "cog", "MdEmoji"),
    ("heart", "plus", "MdEmoji"),
    ("heart", "minus", "MdEmoji"),
    ("heart", "remove", "MdEmoji"),
    ("heart", "off", "MdEmoji"),
    ("water", "ladder", "MdSport"),
    ("water", "polo", "MdSport"),
    ("water", "pump", "MdHome"),
    ("water", "boiler", "MdHome"),
    ("water", "heater", "MdHome"),
    ("water", "percent", "MdScience"),
    ("water", "alert", "MdWeather"),
    ("water", "check", "MdWeather"),
    ("water", "minus", "MdWeather"),
    ("water", "plus", "MdWeather"),
    ("water", "remove", "MdWeather"),
    ("water", "off", "MdWeather"),
    ("water", "sync", "MdWeather"),
    ("water", "circle", "MdWeather"),
    ("water", "outline", "MdWeather"),
    ("water", "opacity", "MdScience"),
    ("water", "thermometer", "MdScience"),
    ("water", "well", "MdHome"),
    ("water", "tap", "MdHome"),
    ("water", "sync", "MdWeather"),
    ("fire", "truck", "MdTransport"),
    ("fire", "extinguisher", "MdTool"),
    ("fire", "hydrant", "MdTool"),
    ("fire", "alert", "MdAlert"),
    ("fire", "circle", "MdWeather"),
    ("flag", "triangle", "MdNavigation"),
    ("flag", "variant", "MdNavigation"),
    ("flag", "outline", "MdNavigation"),
    ("flag", "plus", "MdNavigation"),
    ("flag", "remove", "MdNavigation"),
    ("flag", "checkered", "MdSport"),
    ("car", "brake", "MdTransport"),
    ("car", "seat", "MdTransport"),
    ("car", "door", "MdTransport"),
    ("car", "window", "MdTransport"),
    ("car", "tire", "MdTransport"),
    ("car", "battery", "MdBattery"),
    ("car", "electric", "MdTransport"),
    ("car", "sports", "MdTransport"),
    ("car", "estate", "MdTransport"),
    ("car", "hatchback", "MdTransport"),
    ("car", "pickup", "MdTransport"),
    ("car", "limousine", "MdTransport"),
    ("car", "convertible", "MdTransport"),
    ("car", "cog", "MdTransport"),
    ("car", "connected", "MdTransport"),
    ("car", "info", "MdTransport"),
    ("car", "key", "MdTransport"),
    ("car", "off", "MdTransport"),
    ("car", "settings", "MdTransport"),
    ("car", "wash", "MdTransport"),
    ("car", "arrow", "MdTransport"),
    ("car", "back", "MdTransport"),
    ("car", "child", "MdTransport"),
    ("car", "clock", "MdTransport"),
    ("car", "defrost", "MdTransport"),
    ("car", "emergency", "MdTransport"),
    ("car", "esp", "MdTransport"),
    ("car", "light", "MdTransport"),
    ("car", "multiple", "MdTransport"),
    ("car", "parking", "MdTransport"),
    ("car", "shift", "MdTransport"),
    ("car", "side", "MdTransport"),
    ("car", "speed", "MdTransport"),
    ("car", "traction", "MdTransport"),
    ("car", "turbocharger", "MdTransport"),
    ("car", "wrench", "MdTool"),
    ("home", "floor", "MdHome"),
    ("home", "circle", "MdHome"),
    ("home", "city", "MdBuilding"),
    ("home", "group", "MdBuilding"),
    ("home", "modern", "MdBuilding"),
    ("home", "variant", "MdHome"),
    ("home", "outline", "MdHome"),
    ("home", "account", "MdAccount"),
    ("home", "alert", "MdAlert"),
    ("home", "analytics", "MdFinance"),
    ("home", "assistant", "MdHome"),
    ("home", "automation", "MdHome"),
    ("home", "battery", "MdBattery"),
    ("home", "clock", "MdTime"),
    ("home", "currency", "MdFinance"),
    ("home", "edit", "MdHome"),
    ("home", "export", "MdAction"),
    ("home", "flood", "MdWeather"),
    ("home", "heart", "MdEmoji"),
    ("home", "import", "MdAction"),
    ("home", "lightbulb", "MdHome"),
    ("home", "lightning", "MdWeather"),
    ("home", "lock", "MdSecurity"),
    ("home", "map", "MdMap"),
    ("home", "minus", "MdHome"),
    ("home", "plus", "MdHome"),
    ("home", "remove", "MdHome"),
    ("home", "search", "MdAction"),
    ("home", "settings", "MdHome"),
    ("home", "switch", "MdHome"),
    ("home", "thermometer", "MdHome"),
    ("home", "wifi", "MdDevice"),
    ("human", "male", "MdAccount"),
    ("human", "female", "MdAccount"),
    ("human", "baby", "MdAccount"),
    ("human", "child", "MdAccount"),
    ("human", "elderly", "MdAccount"),
    ("human", "wheelchair", "MdAccount"),
    ("human", "handsup", "MdAccount"),
    ("human", "handsdown", "MdAccount"),
    ("human", "greeting", "MdAccount"),
    ("human", "queue", "MdAccount"),
    ("human", "cane", "MdAccount"),
    ("human", "pregnant", "MdAccount"),
    ("human", "non", "MdAccount"),
    ("human", "capacities", "MdAccount"),
    ("human", "scooter", "MdTransport"),
    ("human", "dolly", "MdShopping"),
    ("human", "edit", "MdAccount"),
    ("human", "male", "MdAccount"),
    ("account", "tie", "MdAccount"),
    ("account", "group", "MdAccount"),
    ("account", "multiple", "MdAccount"),
    ("account", "circle", "MdAccount"),
    ("account", "box", "MdAccount"),
    ("account", "card", "MdFinance"),
    ("account", "cash", "MdFinance"),
    ("account", "check", "MdAccount"),
    ("account", "clock", "MdAccount"),
    ("account", "cog", "MdAccount"),
    ("account", "convert", "MdAccount"),
    ("account", "cowboy", "MdClothing"),
    ("account", "details", "MdAccount"),
    ("account", "edit", "MdAccount"),
    ("account", "eye", "MdAccount"),
    ("account", "filter", "MdAction"),
    ("account", "hard", "MdAccount"),
    ("account", "heart", "MdAccount"),
    ("account", "key", "MdSecurity"),
    ("account", "lock", "MdSecurity"),
    ("account", "minus", "MdAccount"),
    ("account", "music", "MdMedia"),
    ("account", "network", "MdDevice"),
    ("account", "off", "MdAccount"),
    ("account", "outline", "MdAccount"),
    ("account", "plus", "MdAccount"),
    ("account", "question", "MdAccount"),
    ("account", "reactivate", "MdAccount"),
    ("account", "remove", "MdAccount"),
    ("account", "search", "MdAction"),
    ("account", "settings", "MdAccount"),
    ("account", "star", "MdAccount"),
    ("account", "supervisor", "MdAccount"),
    ("account", "switch", "MdAccount"),
    ("account", "sync", "MdAccount"),
    ("account", "voice", "MdCommunication"),
    ("account", "wrench", "MdTool"),
    ("cellphone", "basic", "MdDevice"),
    ("cellphone", "check", "MdDevice"),
    ("cellphone", "cog", "MdDevice"),
    ("cellphone", "dock", "MdDevice"),
    ("cellphone", "erase", "MdDevice"),
    ("cellphone", "key", "MdDevice"),
    ("cellphone", "link", "MdDevice"),
    ("cellphone", "lock", "MdDevice"),
    ("cellphone", "marker", "MdDevice"),
    ("cellphone", "message", "MdCommunication"),
    ("cellphone", "nfc", "MdDevice"),
    ("cellphone", "off", "MdDevice"),
    ("cellphone", "play", "MdMedia"),
    ("cellphone", "remove", "MdDevice"),
    ("cellphone", "screenshot", "MdDevice"),
    ("cellphone", "settings", "MdDevice"),
    ("cellphone", "sound", "MdMedia"),
    ("cellphone", "text", "MdCommunication"),
    ("cellphone", "wireless", "MdDevice"),
    ("cellphone", "arrow", "MdDevice"),
    ("cellphone", "charging", "MdBattery"),
    ("cellphone", "information", "MdDevice"),
    ("store", "24", "MdShopping"),
    ("store", "alert", "MdShopping"),
    ("store", "check", "MdShopping"),
    ("store", "clock", "MdShopping"),
    ("store", "cog", "MdShopping"),
    ("store", "edit", "MdShopping"),
    ("store", "marker", "MdMap"),
    ("store", "minus", "MdShopping"),
    ("store", "off", "MdShopping"),
    ("store", "outline", "MdShopping"),
    ("store", "plus", "MdShopping"),
    ("store", "remove", "MdShopping"),
    ("store", "search", "MdShopping"),
    ("store", "settings", "MdShopping"),
    ("cart", "arrow", "MdShopping"),
    ("cart", "check", "MdShopping"),
    ("cart", "heart", "MdShopping"),
    ("cart", "minus", "MdShopping"),
    ("cart", "off", "MdShopping"),
    ("cart", "outline", "MdShopping"),
    ("cart", "plus", "MdShopping"),
    ("cart", "remove", "MdShopping"),
    ("cart", "variant", "MdShopping"),
    ("bag", "personal", "MdShopping"),
    ("bag", "checked", "MdShopping"),
    ("bag", "carry", "MdShopping"),
    ("bag", "suitcase", "MdTransport"),
    ("bag", "suitcase", "MdTransport"),
    ("shopping", "search", "MdShopping"),
    ("shopping", "outline", "MdShopping"),
    ("shopping", "music", "MdShopping"),
    ("shopping", "play", "MdShopping"),
    ("shopping", "sale", "MdShopping"),
    ("flask", "empty", "MdScience"),
    ("flask", "outline", "MdScience"),
    ("flask", "off", "MdScience"),
    ("flask", "plus", "MdScience"),
    ("flask", "minus", "MdScience"),
    ("flask", "remove", "MdScience"),
    ("flask", "round", "MdScience"),
    ("beaker", "alert", "MdScience"),
    ("beaker", "check", "MdScience"),
    ("beaker", "minus", "MdScience"),
    ("beaker", "off", "MdScience"),
    ("beaker", "outline", "MdScience"),
    ("beaker", "plus", "MdScience"),
    ("beaker", "question", "MdScience"),
    ("beaker", "remove", "MdScience"),
    ("atom", "variant", "MdScience"),
    ("microscope", "variant", "MdScience"),
    ("school", "outline", "MdEducation"),
    ("school", "flag", "MdEducation"),
    ("hospital", "building", "MdHealth"),
    ("hospital", "box", "MdHealth"),
    ("hospital", "marker", "MdHealth"),
    ("medical", "bag", "MdHealth"),
    ("medical", "cotton", "MdHealth"),
    ("medical", "mask", "MdHealth"),
    ("cross", "outline", "MdReligion"),
    ("cross", "catholic", "MdReligion"),
    ("cross", "variant", "MdReligion"),
    ("cross", "hairs", "MdHealth"),
    ("church", "outline", "MdReligion"),
    ("mosque", "outline", "MdReligion"),
    ("synagogue", "outline", "MdReligion"),
    ("temple", "hindu", "MdReligion"),
    ("temple", "buddhist", "MdReligion"),
    ("star", "david", "MdReligion"),
    ("star", "crescent", "MdReligion"),
    ("star", "circle", "MdShape"),
    ("star", "four", "MdShape"),
    ("star", "half", "MdShape"),
    ("star", "outline", "MdShape"),
    ("star", "plus", "MdShape"),
    ("star", "minus", "MdShape"),
    ("star", "remove", "MdShape"),
    ("star", "check", "MdShape"),
    ("star", "settings", "MdShape"),
    ("star", "cog", "MdShape"),
    ("star", "box", "MdShape"),
    ("star", "box", "MdShape"),
    ("emoticon", "happy", "MdEmoji"),
    ("emoticon", "sad", "MdEmoji"),
    ("emoticon", "neutral", "MdEmoji"),
    ("emoticon", "angry", "MdEmoji"),
    ("emoticon", "confused", "MdEmoji"),
    ("emoticon", "cool", "MdEmoji"),
    ("emoticon", "cry", "MdEmoji"),
    ("emoticon", "dead", "MdEmoji"),
    ("emoticon", "devil", "MdEmoji"),
    ("emoticon", "excited", "MdEmoji"),
    ("emoticon", "frown", "MdEmoji"),
    ("emoticon", "kiss", "MdEmoji"),
    ("emoticon", "lol", "MdEmoji"),
    ("emoticon", "outline", "MdEmoji"),
    ("emoticon", "poop", "MdEmoji"),
    ("emoticon", "sick", "MdEmoji"),
    ("emoticon", "tongue", "MdEmoji"),
    ("emoticon", "wink", "MdEmoji"),
    ("face", "man", "MdAccount"),
    ("face", "woman", "MdAccount"),
    ("face", "profile", "MdAccount"),
    ("face", "recognition", "MdSecurity"),
    ("face", "agent", "MdAccount"),
    ("tree", "outline", "MdNature"),
    ("flower", "outline", "MdNature"),
    ("flower", "poppy", "MdNature"),
    ("flower", "tulip", "MdNature"),
    ("leaf", "maple", "MdNature"),
    ("leaf", "circle", "MdNature"),
    ("leaf", "off", "MdNature"),
    ("pine", "tree", "MdNature"),
    ("palm", "tree", "MdNature"),
    ("soccer", "field", "MdSport"),
    ("basketball", "hoop", "MdSport"),
    ("football", "helmet", "MdSport"),
    ("football", "australian", "MdSport"),
    ("baseball", "bat", "MdSport"),
    ("baseball", "diamond", "MdSport"),
    ("tennis", "ball", "MdSport"),
    ("tennis", "racquet", "MdSport"),
    ("golf", "tee", "MdSport"),
    ("golf", "cart", "MdSport"),
    ("hockey", "sticks", "MdSport"),
    ("ski", "cross", "MdSport"),
    ("ski", "water", "MdSport"),
    ("ski", "cross", "MdSport"),
    ("weight", "lifter", "MdSport"),
    ("weight", "pound", "MdSport"),
    ("weight", "kilogram", "MdSport"),
    ("trophy", "award", "MdSport"),
    ("trophy", "variant", "MdSport"),
    ("trophy", "outline", "MdSport"),
    ("trophy", "broken", "MdSport"),
    ("medal", "outline", "MdSport"),
    ("shirt", "crew", "MdClothing"),
    ("shirt", "vneck", "MdClothing"),
    ("shoe", "formal", "MdClothing"),
    ("shoe", "sneaker", "MdClothing"),
    ("shoe", "ballet", "MdClothing"),
    ("shoe", "cleat", "MdClothing"),
    ("shoe", "heel", "MdClothing"),
    ("hat", "fedora", "MdClothing"),
    ("tie", "variant", "MdClothing"),
    ("tie", "outline", "MdClothing"),
    ("briefcase", "account", "MdOffice"),
    ("briefcase", "check", "MdOffice"),
    ("briefcase", "clock", "MdOffice"),
    ("briefcase", "download", "MdOffice"),
    ("briefcase", "edit", "MdOffice"),
    ("briefcase", "eye", "MdOffice"),
    ("briefcase", "minus", "MdOffice"),
    ("briefcase", "off", "MdOffice"),
    ("briefcase", "outline", "MdOffice"),
    ("briefcase", "plus", "MdOffice"),
    ("briefcase", "remove", "MdOffice"),
    ("briefcase", "search", "MdOffice"),
    ("briefcase", "upload", "MdOffice"),
    ("briefcase", "variant", "MdOffice"),
    ("briefcase", "medical", "MdHealth"),
    ("desk", "lamp", "MdOffice"),
    ("desk", "phone", "MdOffice"),
    ("desk", "clock", "MdOffice"),
    ("desk", "access", "MdOffice"),
    ("office", "building", "MdBuilding"),
    ("office", "building", "MdBuilding"),
    ("city", "variant", "MdBuilding"),
    ("factory", "variant", "MdBuilding"),
    ("warehouse", "variant", "MdBuilding"),
    ("domain", "plus", "MdDevice"),
    ("domain", "minus", "MdDevice"),
    ("domain", "remove", "MdDevice"),
    ("domain", "off", "MdDevice"),
    ("domain", "switch", "MdDevice"),
    ("domain", "refresh", "MdDevice"),
    ("domain", "arrow", "MdDevice"),
    ("wrench", "clock", "MdTool"),
    ("wrench", "outline", "MdTool"),
    ("wrench", "cog", "MdTool"),
    ("hammer", "screwdriver", "MdTool"),
    ("hammer", "wrench", "MdTool"),
    ("screwdriver", "variant", "MdTool"),
    ("screwdriver", "flat", "MdTool"),
    ("axe", "battle", "MdTool"),
    ("saw", "blade", "MdTool"),
    ("saw", "circular", "MdTool"),
    ("saw", "hand", "MdTool"),
    ("cat", "variant", "MdAnimal"),
    ("dog", "variant", "MdAnimal"),
    ("dog", "service", "MdAnimal"),
    ("dog", "side", "MdAnimal"),
    ("bird", "variant", "MdAnimal"),
    ("fish", "variant", "MdAnimal"),
    ("fish", "bowl", "MdAnimal"),
    ("fish", "off", "MdAnimal"),
    ("rabbit", "variant", "MdAnimal"),
    ("cow", "variant", "MdAnimal"),
    ("pig", "variant", "MdAnimal"),
    ("horse", "variant", "MdAnimal"),
    ("horse", "human", "MdAnimal"),
    ("spider", "variant", "MdAnimal"),
    ("bee", "variant", "MdAnimal"),
    ("butterfly", "variant", "MdAnimal"),
    ("snail", "variant", "MdAnimal"),
    ("turtle", "variant", "MdAnimal"),
    ("elephant", "variant", "MdAnimal"),
    ("panda", "variant", "MdAnimal"),
    ("penguin", "variant", "MdAnimal"),
    ("owl", "variant", "MdAnimal"),
    ("bat", "variant", "MdAnimal"),
    ("shark", "variant", "MdAnimal"),
    ("whale", "variant", "MdAnimal"),
    ("dolphin", "variant", "MdAnimal"),
    ("kangaroo", "variant", "MdAnimal"),
    ("koala", "variant", "MdAnimal"),
    ("monkey", "variant", "MdAnimal"),
    ("snake", "variant", "MdAnimal"),
    ("ladybug", "variant", "MdAnimal"),
    ("food", "apple", "MdFood"),
    ("food", "drumstick", "MdFood"),
    ("food", "fork", "MdFood"),
    ("food", "off", "MdFood"),
    ("food", "outline", "MdFood"),
    ("food", "steak", "MdFood"),
    ("food", "turkey", "MdFood"),
    ("food", "variant", "MdFood"),
    ("fruit", "cherry", "MdFood"),
    ("fruit", "citrus", "MdFood"),
    ("fruit", "grapes", "MdFood"),
    ("fruit", "pear", "MdFood"),
    ("fruit", "pineapple", "MdFood"),
    ("fruit", "watermelon", "MdFood"),
    ("zodiac", "aries", "MdReligion"),
    ("zodiac", "taurus", "MdReligion"),
    ("zodiac", "gemini", "MdReligion"),
    ("zodiac", "cancer", "MdReligion"),
    ("zodiac", "leo", "MdReligion"),
    ("zodiac", "virgo", "MdReligion"),
    ("zodiac", "libra", "MdReligion"),
    ("zodiac", "scorpio", "MdReligion"),
    ("zodiac", "sagittarius", "MdReligion"),
    ("zodiac", "capricorn", "MdReligion"),
    ("zodiac", "aquarius", "MdReligion"),
    ("zodiac", "pisces", "MdReligion"),
]

# First-segment -> domain for all non-brand segments.
# Built from semantic keyword groups; generator fills gaps from icon data.
SEGMENT_DOMAINS: dict[str, str] = {}
