set(TUINATOR_BACKEND_SOURCES
    src/backend/curses_backend.cpp
    src/backend/inline_backend.cpp
    src/backend/memory_backend.cpp
    src/backend/terminal_backend.cpp
)

set(TUINATOR_CORE_SOURCES
    src/core/action_registry.cpp
    src/core/application.cpp
    src/core/inline_view.cpp
    src/debug/startup_profiler.cpp
    src/layout/box.cpp
    src/layout/grid.cpp
    src/render/canvas.cpp
    src/render/color.cpp
    src/render/graphics_encode.cpp
    src/render/graphics_protocol.cpp
    src/render/file_icon.cpp
    src/render/git_change_status.cpp
    src/render/ui_icon.cpp
    src/render/line_icon.cpp
    src/render/nerd_icon_set.cpp
    src/render/weather_icon.cpp
    src/render/moon_icon.cpp
    src/render/clock_icon.cpp
    src/render/compass_icon.cpp
    src/render/measurement_icon.cpp
    src/render/astronomy_icon.cpp
    src/render/air_quality_icon.cpp
    src/render/hazard_icon.cpp
    src/render/marine_alert_icon.cpp
    src/render/action_icon.cpp
    src/render/nerd_glyph_catalog.cpp
    src/render/block_element.cpp
    src/render/box_drawing.cpp
    src/render/glyphs.cpp
    src/render/scrollbar/core.cpp
    src/render/scrollbar/behavior.cpp
    src/render/scrollbar/style.cpp
    src/render/scrollbar/scrollbar.cpp
    src/render/terminal_image.cpp
    src/render/text.cpp
    src/render/theme.cpp
    src/widgets/widget.cpp
    src/widgets/capabilities.cpp
    src/widgets/controls/button.cpp
    src/widgets/controls/checkbox.cpp
    src/widgets/controls/combo_box.cpp
    src/widgets/controls/slider.cpp
    src/widgets/controls/text_area.cpp
    src/widgets/controls/text_input.cpp
    src/widgets/controls/toggle.cpp
    src/widgets/display/big_text.cpp
    src/widgets/display/image_view.cpp
    src/widgets/display/label.cpp
    src/widgets/display/nerd_icon_catalog_gallery.cpp
    src/widgets/display/nerd_glyph_matrix_gallery.cpp
    src/widgets/display/progress_bar.cpp
    src/widgets/display/separator.cpp
    src/widgets/display/spinner.cpp
    src/widgets/display/throbber.cpp
    src/widgets/containers/panel.cpp
    src/widgets/containers/scroll_view.cpp
    src/widgets/containers/split_pane.cpp
    src/widgets/containers/tabs.cpp
    src/widgets/views/list_view.cpp
    src/widgets/views/table.cpp
    src/widgets/views/tree_view.cpp
    src/widgets/charts/bar_chart.cpp
    src/widgets/charts/candlestick_chart.cpp
    src/widgets/charts/chart_common.cpp
    src/widgets/charts/gauge_chart.cpp
    src/widgets/charts/heatmap.cpp
    src/widgets/charts/histogram.cpp
    src/widgets/charts/line_chart.cpp
    src/widgets/charts/pie_chart.cpp
    src/widgets/charts/stacked_area_chart.cpp
    src/widgets/charts/waterfall_chart.cpp
    src/widgets/menu/command_palette.cpp
    src/widgets/menu/context_menu.cpp
    src/widgets/menu/menu_bar.cpp
    src/widgets/menu/menu_common.cpp
    src/widgets/chrome/dialog.cpp
    src/widgets/chrome/source_control_panel.cpp
    src/widgets/chrome/status_bar.cpp
    src/widgets/chrome/status_line.cpp
    src/widgets/chrome/terminal_frame.cpp
    src/widgets/chrome/shell_terminal.cpp
    src/terminal/ansi_terminal_buffer.cpp
    src/terminal/pty_session.cpp
    src/window/desktop.cpp
    src/window/window.cpp
    src/window/window_manager.cpp
    src/window/window_host.cpp
    src/scene/handler_registry.cpp
    src/scene/scene_context.cpp
    src/scene/scene_builder.cpp
    src/scene/detail/json_node.cpp
    src/scene/detail/style_resolve.cpp
    src/scene/detail/binding_engine.cpp
    src/scene/runtime/widget_builder.generated.cpp
)

set(TUINATOR_SOURCES
    ${TUINATOR_BACKEND_SOURCES}
    ${TUINATOR_CORE_SOURCES}
)
